FEATURE: Store Data for Genre and Album
adamteddychang/catalog-of-my-things pull request #59
Opened 2022-02-08 14:34 UTC by luftedar

# FEATURE: Store Data for Genre and Album
### Hello @adamteddychang  :wave: 

In this update:

- Created a module called `DataStore`
- Add data preservation by using `.json` files for the `Genre` and `MusicAlbum` Classes.

Have a nice CR. :+1:

2022-02-08 14:44 UTC, adamteddychang requested changes
Great work so far! Here are some changes that needs to be done:

2022-02-08 14:44 UTC, adamteddychang commented on data_store.rb
> +        MusicAlbum.new(album['name'], album['genre'], album['label'], album['publish_date'], album['on_spotify'])
There is a missing parameter while saving into the json file, causing the data to shift one spot to the left.

2022-02-08 14:44 UTC, adamteddychang commented on data_store.rb
> +        Genre.new(genre['name'])
The data isn't saving to genre.json

2022-02-08 15:16 UTC, luftedar commented
Hey @adamteddychang. Made required changes.

2022-02-08 16:02 UTC, adamteddychang requested changes
Great work on this milestone! 
I have added the requested changes as comments. 
Keep up the good work!

2022-02-08 16:02 UTC, adamteddychang commented on app.rb
>      @genres.each { |genre| puts genre }
Line 45 should be `@genres.each do |genre|
      puts "[#{genre.id}], Name: #{genre.name}"
    end` so it will list correctly from json

2022-02-08 16:02 UTC, adamteddychang commented on data_store.rb
> +        MusicAlbum.new(album['name'], album['genre'], album['label'], album['publish_date'], album['on_spotify'])
Should remove Label from the parameters and add id in the beginning 
`MusicAlbum.new(album['id'],album['name'], album['genre'], album['publish_date'], album['on_spotify'])`

2022-02-08 16:02 UTC, adamteddychang commented on data_store.rb
> +        Genre.new(genre['name'])
Should add the parameter of id in genre on line 19
`Genre.new(genre['id'], genre['name'])`

2022-02-09 08:37 UTC, adamteddychang approved these changes
Great work! 
This milestone has been approved! 
![clapping-leonardo-dicaprio](https://user-images.githubusercontent.com/63560332/153157173-8623baab-1e55-4cc6-bee8-defe8a9f20a8.gif)

2022-02-09 08:47 UTC, merged